---
- name: Create opengist user
  ansible.builtin.user:
    name: "{{ opengist_container_user }}"
    shell: /sbin/nologin
    create_home: true
    state: present
  become: true

- name: Get created user metadata
  ansible.builtin.getent:
    database: passwd
    key: "{{ opengist_container_user }}"

- name: Setting user id and group id facts
  ansible.builtin.set_fact:
    created_uid: "{{ ansible_facts.getent_passwd[opengist_container_user].1 }}"
    created_gid: "{{ ansible_facts.getent_passwd[opengist_container_user].2 }}"

- name: Ensure opengist folders exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ opengist_container_user }}"
    group: "{{ opengist_container_user }}"
    state: directory
    mode: 0755
  loop:
    - "{{ opengist_host_config_path }}"

- name: Copy opengist docker-compose template.
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ opengist_host_config_path }}/docker-compose.yml"
    owner: "{{ opengist_container_user }}"
    group: "{{ opengist_container_user }}"
    mode: 0644
  become: true

- name: Create systemd opengist service.
  ansible.builtin.template:
    src: templates/opengist.service.j2
    dest: "/etc/systemd/system/opengist.service"
    mode: 0644
  become: true

- name: Ensure opengist.service is started
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: opengist
  become: true

- name: Check opengist container
  ansible.builtin.uri:
    url: "http://localhost:{{ opengist_host_port }}"
    status_code: [200, 401]
  register: result
  until: result.status == 200 or result.status == 401
  retries: 5
  delay: 60

- name: Remove old image versions
  become: true
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false
  notify: Restart Docker service
